import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { AppProps } from "next/app";
import AuthContextProvider from "../modules/auth_provider";
import WebSocketProvider from "../modules/websocket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <WebSocketProvider>
          <body className={inter.className}>{children}</body>
        </WebSocketProvider>
      </AuthContextProvider>
    </html>
  );
}
